/*
 * action types
 */

export const UPDATE_TOKEN = 'UPDATE_TOKEN';

export const ADD_IMAGE = 'ADD_IMAGE';
export const UPDATE_IMAGE = 'UPDATE_IMAGE';
export const REMOVE_IMAGE = 'REMOVE_IMAGE';

export const ADD_SOUND = 'ADD_SOUND';
export const UPDATE_SOUND = 'UPDATE_SOUND';
export const REMOVE_SOUND = 'REMOVE_SOUND';

export const UPDATE_SPIN_CHANCES = 'UPDATE_SPIN_CHANCES';

export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';

export const UPDATE_MONEY = 'UPDATE_MONEY';

export const UPDATE_REPEATS = 'UPDATE_REPEATS';

export const UPDATE_DISCOUNT = 'UPDATE_DISCOUNT';

export const UPDATE_WINDOWS = 'UPDATE_WINDOWS';
export const UPDATE_WIDGET = 'UPDATE_WIDGET';

export const ADD_LAYER = 'ADD_LAYER';
export const UPDATE_LAYER = 'UPDATE_LAYER';
export const REMOVE_LAYER = 'REMOVE_LAYER';
export const UP_LAYER = 'UP_LAYER';
export const DOWN_LAYER = 'DOWN_LAYER';

export const UPDATE_ROULETTE_APPEARANCE = 'UPDATE_ROULETTE_APPEARANCE';
export const UPDATE_ROULETTE_SPIN = 'UPDATE_ROULETTE_SPIN';

export const UPDATE_ROULETTE_IMAGES = 'UPDATE_ROULETTE_IMAGES';
export const UPDATE_ROULETTE_SOUNDS = 'UPDATE_ROULETTE_SOUNDS';

export const UPDATE_WINDOW_STATE = 'UPDATE_WINDOW_STATE';
export const ADD_SPIN_RESULT = 'ADD_SPIN_RESULT';
export const UPDATE_EARNED = 'UPDATE_EARNED';
export const UPDATE_CURRENT_AMOUNT = 'UPDATE_CURRENT_AMOUNT';
export const UPDATE_CURRENT_DONATE = 'UPDATE_CURRENT_DONATE';
export const UPDATE_CURRENT_STATE = 'UPDATE_CURRENT_STATE';
export const UPDATE_DISCOUNT_EARNED = 'UPDATE_DISCOUNT_EARNED';

export const UPDATE_SYSTEM = 'UPDATE_SYSTEM';